# Site settings

author: Coruna
email: example@email.com

head-title: Rezensionen # Browserheader
title: Corunas Rezensionen

baseurl: ""    # the subpath of your site, "/blog"
url: ""

# footer 
# description: "I know that what I'm doing looks stupid, but I'm a big boy and really want to do this."

favo: "Über diese Seite"
descrpt: "Hier findet ihr Rezensionen zu Büchern, die ich gelesen habe. Die Seite ist tatsächlich eher für mich selber gedacht, damit ich meinen Lesekonsum im Blick behalte. Vielleicht ist es aber ja auch für euch interessant. "


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

plugins: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "grey darken-1"
head-theme-color: "#757575"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "grey darken-1"
footer-button-color: "grey darken-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

